### ISSUE TITLE
incorrect using of mktemp

### ISSUE THREAD

**Issue by CompuRoot** [shinokada/tera#1]
script failed with error: `mktemp: too few X's in template ‘/tmp/radio_searches.json’`

mktemp(1) - Linux man page:

>TEMPLATE **must** contain at least 3 consecutive 'X's in last component.

If you using your own template, you have to name temporary file for example as: `/tmp/radio_searches.XXXXXXX.json`

where `XXXXXXX` will be replaced dynamically to random characters to prevent name overcrosing.

Also, suggestion: use `trap` to clean temporary files automatically for the purpose not only simplify cleaning but also remove trash in case system shutdown, Ctrl+C and so on

**Comment by shinokada** [comment]
Can you run `awesome update tera` and test it again?

Thank you for the bug report.

**Comment by CompuRoot** [comment]
> And test it again?

I updated via `git pull` and tried again, previous error went away, but when I choose `2) Search radio station` and found radio I wanted by `2) Name` and choose to save station `2) Save` to `1) default` list, then from root menu I selected    
`1) Play from my list` and got this error:

```
/full/path/to/tera/lib: line 70: ((: > 0: syntax error: operand expected (error token is "> 0")
```

**Comment by shinokada** [comment]
@CompuRoot Thank you.
It should work now.
The default file didn't have `[]` to add the json item.
You will see the sample list.
Please remove `~/.terminalradio` folder before running `tera`.

**Comment by CompuRoot** [comment]
> It should work now.

Yes, it works now, thank you !
