### ISSUE TITLE
Any way to install it on Arch

### ISSUE THREAD

**Issue by tanaybhomia** [shinokada/tera#2]
I am not able to find a AUR package or any Manjaro community package for this and I really like this concept. How can I get it

**Comment by donnaber** [comment]
I can't find the source code. That's fishy.

**Comment by shinokada** [comment]
I'm sorry. I don't know how to create a package for ArchLinux. I will see what I can do.
Tera works on Ubuntu and macOS. I used Bash script.
If anyone knows how to create a ArchLinux package, I will appreciate the contribution.

**Comment by shinokada** [comment]
Please see the [release page](https://github.com/shinokada/tera/releases/tag/v0.4.1).

**Comment by donnaber** [comment]
I'll try to make the Arch Package.

**Comment by shinokada** [comment]
Awesome!
Thank you @donnaber.

**Comment by Hibbins** [comment]
I just added this, so if you want to close this issue, I believe you would be able to now! :)

Link: https://aur.archlinux.org/packages/tera

@shinokada
