### ISSUE TITLE
[BUG]: Advanced search error

### ISSUE THREAD

**Issue by antonellocaroli** [shinokada/tera#8]
### Description of the bug

when I try Advanced search I always get an error

### Steps To Reproduce

TERA SEARCH MENU:
1) Tag
2) Name
3) Language 
4) Country code
5) State
6) Advanced search
7) Main Menu
0) Exit
Choose an option: 6
The query format is -d field=word.
Field can be one of tag, name, language, country code and state.
Fields can be combined, for example: -d tag=jazz -d state=queensland
Or tag=rock language=spanish countrycode=us
Or tag=country state=IL
Write your quiry: tag=country state=IL
tag=country
/usr/share/tera/lib/lib.sh: line 140: KEY: unbound variable

**Comment by shinokada** [comment]
You are missing `-d`:

```
 -d tag=country -d state=IL
```

**Comment by antonellocaroli** [comment]
TERA MAIN MENU
1) Play from my list
2) Search radio stations
3) List (Create/Read/Update/Delete)
4) Delete a radio station 
5) I feel lucky
6) Gist
0) Exit
Choose an option: 2

TERA SEARCH MENU:
1) Tag
2) Name
3) Language 
4) Country code
5) State
6) Advanced search
7) Main Menu
0) Exit
Choose an option: 6
The query format is -d field=word.
Field can be one of tag, name, language, country code and state.
Fields can be combined, for example: -d tag=jazz -d state=queensland
Or tag=rock language=spanish countrycode=us
Or tag=country state=IL
Write your quiry: -d tag=country -d state=IL
-d
/usr/share/tera/lib/lib.sh: line 140: KEY: unbound variable

**Comment by shinokada** [comment]
You don't need `-d` at the end.

**Comment by antonellocaroli** [comment]
in Bold is output

TERA MAIN MENU
1) Play from my list
2) Search radio stations
3) List (Create/Read/Update/Delete)
4) Delete a radio station 
5) I feel lucky
6) Gist
0) Exit
Choose an option: 2

TERA SEARCH MENU:
1) Tag
2) Name
3) Language
4) Country code
5) State
6) Advanced search
7) Main Menu
0) Exit
Choose an option: 6
The query format is -d field=word.
Field can be one of tag, name, language, country code and state.
Fields can be combined, for example: -d tag=jazz -d state=queensland
Or tag=rock language=spanish countrycode=us
Or tag=country state=IL
Write your quiry: -d tag=jazz
```
-d
/usr/share/tera/lib/lib.sh: line 150: KEY: unbound variable
```

TERA MAIN MENU
1) Play from my list
2) Search radio stations
3) List (Create/Read/Update/Delete)
4) Delete a radio station 
5) I feel lucky
6) Gist
0) Exit
Choose an option: 2

TERA SEARCH MENU:
1) Tag
2) Name
3) Language
4) Country code
5) State
6) Advanced search
7) Main Menu
0) Exit
Choose an option: 6
The query format is -d field=word.
Field can be one of tag, name, language, country code and state.
Fields can be combined, for example: -d tag=jazz -d state=queensland
Or tag=rock language=spanish countrycode=us
Or tag=country state=IL
Write your quiry: tag=jazz
```
tag=jazz
/usr/share/tera/lib/lib.sh: line 150: KEY: unbound variable
```

TERA MAIN MENU
1) Play from my list
2) Search radio stations
3) List (Create/Read/Update/Delete)
4) Delete a radio station 
5) I feel lucky
6) Gist
0) Exit
Choose an option: 2

TERA SEARCH MENU:
1) Tag
2) Name
3) Language
4) Country code
5) State
6) Advanced search
7) Main Menu
0) Exit
Choose an option: 6
The query format is -d field=word.
Field can be one of tag, name, language, country code and state.
Fields can be combined, for example: -d tag=jazz -d state=queensland
Or tag=rock language=spanish countrycode=us
Or tag=country state=IL
Write your quiry: -d tag=jazz state=queensland                       
```
-d
/usr/share/tera/lib/lib.sh: line 150: KEY: unbound variable
```

**Comment by shinokada** [comment]
What is your Bash version?

**Comment by antonellocaroli** [comment]
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)

**Comment by shinokada** [comment]
Does all other functions work?

**Comment by antonellocaroli** [comment]
yes

**Comment by shinokada** [comment]
What is your OS? Are you using Mac and Homebrew?

**Comment by antonellocaroli** [comment]
Gentoo linux
